<?php

use GuzzleHttp\RequestOptions;
use Spatie\Sitemap\Crawler\Profile;

return [

    /*
     * These options will be passed to GuzzleHttp\Client when it is created.
     * For in-depth information on all options see the Guzzle docs:
     *
     * http://docs.guzzlephp.org/en/stable/request-options.html
     */
    'guzzle_options' => [

        /*
         * Whether or not cookies are used in a request.
         * Enabled for session handling during crawling.
         */
        RequestOptions::COOKIES => true,

        /*
         * The number of seconds to wait while trying to connect to a server.
         * Set to 10 seconds for a good balance between speed and reliability.
         */
        RequestOptions::CONNECT_TIMEOUT => 10,

        /*
         * The timeout of the request in seconds.
         * Use 10 seconds to avoid hanging indefinitely.
         */
        RequestOptions::TIMEOUT => 10,

        /*
         * Describes the redirect behavior of a request.
         * Enable redirects to handle SEO-related redirections during crawling.
         */
        RequestOptions::ALLOW_REDIRECTS => true, // Updated to `true` for following redirects
    ],

    /*
     * The sitemap generator can execute JavaScript on each page so it will
     * discover links that are generated by your JS scripts. This feature
     * is powered by headless Chrome.
     */
    'execute_javascript' => false, // Leave as `false` unless your site relies heavily on JS for rendering content.

    /*
     * The package will make an educated guess as to where Google Chrome is installed.
     * You can also manually pass its location here if automatic detection fails.
     */
    'chrome_binary_path' => null,

    /*
     * The sitemap generator uses a CrawlProfile implementation to determine
     * which URLs should be crawled for the sitemap.
     * You can implement your own profile if needed.
     */
    'crawl_profile' => Profile::class,

];
